import { FinancialProduct } from "../../../domain/entities/financialProduct";

export const financialProducts: FinancialProduct[] = [
    {
        id: 'trj-crd',
        name: 'Tarjetas de credito',
        description: 'Tarjeta de consumo bajo la modalidad de credito',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2021-03-10"),
        date_revision: new Date("2023-09-15"),
    },
    {
        id: 'cta-ah',
        name: 'Cuenta de Ahorros',
        description: 'Cuenta de ahorros para tus finanzas personales',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2020-07-25"),
        date_revision: new Date("2023-11-04"),
    },
    {
        id: 'prest-per',
        name: 'Préstamo Personal',
        description: 'Préstamo personal para tus proyectos',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2019-12-15"),
        date_revision: new Date("2023-08-20"),
    },
    {
        id: 'trj-deb',
        name: 'Tarjeta de Débito',
        description: 'Tarjeta de débito para tus transacciones diarias',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2021-05-05"),
        date_revision: new Date("2023-10-10"),
    },
    {
        id: 'prest-hip',
        name: 'Préstamo Hipotecario',
        description: 'Préstamo para adquirir una vivienda',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2020-10-20"),
        date_revision: new Date("2023-07-15"),
    },
    {
        id: 'inv-fond',
        name: 'Fondos de Inversión',
        description: 'Opciones de inversión para hacer crecer tu dinero',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2020-09-10"),
        date_revision: new Date("2023-04-01"),
    },
    {
        id: 'seg-auto',
        name: 'Seguro de Auto',
        description: 'Seguro de auto para proteger tu vehículo',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2020-12-05"),
        date_revision: new Date("2023-07-30"),
    },
    {
        id: 'cta-cor',
        name: 'Cuenta Corriente',
        description: 'Cuenta corriente para operaciones bancarias',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2021-02-15"),
        date_revision: new Date("2023-08-10"),
    },
    {
        id: 'inv-plaz',
        name: 'Inversiones a Plazo',
        description: 'Inversiones con plazo fijo para ganar intereses',
        logo: 'https://www.example.com/inversiones-plazo.jpg',
        date_release: new Date("2019-10-10"),
        date_revision: new Date("2023-06-20"),
    },
    {
        id: 'app-mov',
        name: 'Aplicación Móvil',
        description: 'App móvil para gestionar tus finanzas',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2021-04-20"),
        date_revision: new Date("2023-10-05"),
    },
    {
        id: 'tarj-prep',
        name: 'Tarjeta Prepago',
        description: 'Tarjeta prepago para compras seguras',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2020-08-30"),
        date_revision: new Date("2023-09-25"),
    },
    {
        id: 'cre-auto',
        name: 'Crédito Automotriz',
        description: 'Crédito para comprar un vehículo',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2020-06-10"),
        date_revision: new Date("2023-04-15"),
    },
    {
        id: 'seg-hog',
        name: 'Seguro de Hogar',
        description: 'Seguro para proteger tu vivienda',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2019-08-20"),
        date_revision: new Date("2023-11-15"),
    },
    {
        id: 'empresarial',
        name: 'Cuenta Empresarial',
        description: 'Cuenta bancaria para empresas',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2021-01-10"),
        date_revision: new Date("2023-06-05"),
    },
    {
        id: 'tasa-int',
        name: 'Tasas de Interés',
        description: 'Información sobre tasas de interés',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2020-04-05"),
        date_revision: new Date("2023-03-20"),
    },
    {
        id: 'seg-salud',
        name: 'Seguro de Salud',
        description: 'Seguro de salud para tu bienestar',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2019-06-25"),
        date_revision: new Date("2023-05-10"),
    },
    {
        id: 'cre-emp',
        name: 'Crédito Empresarial',
        description: 'Crédito para impulsar tu negocio',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2021-02-28"),
        date_revision: new Date("2023-07-20"),
    },
    {
        id: 'inv-ret',
        name: 'Inversiones a Retiro',
        description: 'Inversiones para asegurar tu retiro',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2020-10-30"),
        date_revision: new Date("2023-06-10"),
    },
    {
        id: 'seg-vida',
        name: 'Seguro de Vida',
        description: 'Seguro de vida para proteger a tus seres queridos',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2019-12-15"),
        date_revision: new Date("2023-04-30"),
    },
    {
        id: 'cre-edu',
        name: 'Crédito Educativo',
        description: 'Crédito para financiar tu educación',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2021-06-10"),
        date_revision: new Date("2023-09-30"),
    },
    {
        id: 'seg-viaje',
        name: 'Seguro de Viaje',
        description: 'Seguro de viaje para tus aventuras',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2020-09-05"),
        date_revision: new Date("2023-07-05"),
    },
    {
        id: 'cta-inver',
        name: 'Cuenta de Inversiones',
        description: 'Cuenta de inversiones para hacer crecer tu patrimonio',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2021-03-05"),
        date_revision: new Date("2023-10-30"),
    },
    {
        id: 'seg-neg',
        name: 'Seguro de Negocio',
        description: 'Seguro para proteger tu negocio',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2019-10-15"),
        date_revision: new Date("2023-04-10"),
    },
    {
        id: 'cre-cons',
        name: 'Crédito de Consumo',
        description: 'Crédito para tus necesidades de consumo',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2020-07-15"),
        date_revision: new Date("2023-08-30"),
    },
    {
        id: 'tarj-recomp',
        name: 'Tarjeta de Recompensas',
        description: 'Tarjeta que te recompensa por tus compras',
        logo: 'https://www.visa.com.ec/dam/VCOM/regional/lac/SPA/Default/Pay%20With%20Visa/Tarjetas/visa-signature-400x225.jpg',
        date_release: new Date("2021-05-20"),
        date_revision: new Date("2023-09-10"),
    },
];